### ISSUE TITLE
Cloud (AWS) connector

### ISSUE THREAD

**Issue by nineinchnick** [tooptoop4/awesome-prestosql#1]
Hi there, would you like to add yet another one of my connectors to the list? It's for reading (and writing!) AWS data like EC2 instances or S3 buckets: https://github.com/nineinchnick/trino-cloud

There are already two others like this on the list so I'm not sure where exactly to place it.

**Comment by tooptoop4** [comment]
fixed by https://github.com/tooptoop4/awesome-prestosql/commit/f4d8aae6eccf96c877c483bcdc9492212e9a6c8c
